#ifndef SETOPERATIONS_GLOBAL_H
#define SETOPERATIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETOPERATIONS_LIBRARY)
#  define SETOPERATIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SETOPERATIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SETOPERATIONS_GLOBAL_H
